language: java
script:
- mvn verify compile install test package
before_deploy:
- git config --local user.name "DerkVanDenBergh"
- git config --local user.email "derkv@ndenbergh.nl"
- export GIT_TAG=master-v0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
deploy:
  provider: releases
  api_key:
    secure: O5k893tiwUyZDK1q14bJSNUv1ZjcVVW8JQfgVrfG+zoELt8xnxynSadcGtUrA4cx1TfEsoMQYN3zaqy2yKwG+LhpoAAanxg0EJeLjeDu2Wi0NJZMNypNfK7lq5u40a6RHcmfoicEoJS7fKwzrYdFtdSYmUW07uFuCcQAaJRksHf4Dxd1YNeqaDG0Gfo6uWA2+CUhCC7kbTZ+xovG+fCscEa/aT+cwxvB4cZJlrJCFFgZy+KFb9wO5z33UNANtw2DMvlfHcOr3rSj2u+eV1NFPeFIwhQnkmH6H+g+ErodoNsLbYuFwADyKssLDACIWiwESMqUn8+YJj3Wg8DbNSxBN5MupuPOGcp52zbDtc/asZa29PMZRau4hgFVKgpUHCIEtHuR37MWp+qkzMBDrgObwxkDo9hK3oFboNhWt9DohmOx+Pxuv/4xXB1bJ8LE+uQM1hVBNEViLPqr/80MJ/tWIHRtzVjTJB82xqMLJfmITtSuaDLD4SHxeglcc6NXTVxYLKAdYzs3V0KoHzR0+MSjqr/U1AgRYPbe/kVz0twua5ZoyRYzT00zmJheec9VKBIyx3Jj2RtwJTARIivZ84EoshG97FBK6KKkrs3hNSZapVpKRTPTKxt6cs3kAy8qZFD4Aa8rnl7CZ6Dk35svEcWZnUdxsV1DU7tTv74Hhp6e/W4=
  file: './target/Wordset-Export.jar'
  on:
    repo: DerkVanDenBergh/lingo-words
    branch: master
  skip_cleanup: 'true'
